"""initial schema

Captures the full schema as of the FastAPI/PostgreSQL rebuild: 8 tables, 3
domain enum types (+ otp_purpose), all foreign keys, the pg_trgm extension and
its GIN indexes, and the composite btree on items.

Two things autogenerate cannot infer and which are added by hand:

* ``CREATE EXTENSION pg_trgm`` -- required *before* the gin_trgm_ops indexes.
* Explicit enum creation. ``item_status`` is used by both ``items`` and
  ``item_status_events``; left to inline ``sa.Enum`` each ``create_table`` would
  try to CREATE TYPE a second time and fail. The types are therefore created
  once up front with ``checkfirst=True`` and referenced with
  ``create_type=False``.

Revision ID: ac938cefe45e
Revises: 
Create Date: 2026-08-23 11:52:38.092709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ac938cefe45e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# --- enum types -------------------------------------------------------------
# Created once in upgrade(); referenced with create_type=False everywhere else.
ITEM_KIND_VALUES = ("lost", "found")
ITEM_STATUS_VALUES = ("reported", "matched", "claimed", "closed")
CLAIM_STATUS_VALUES = ("pending", "approved", "rejected")
OTP_PURPOSE_VALUES = ("registration", "password_reset")

ITEM_KIND = postgresql.ENUM(*ITEM_KIND_VALUES, name="item_kind", create_type=False)
ITEM_STATUS = postgresql.ENUM(*ITEM_STATUS_VALUES, name="item_status", create_type=False)
CLAIM_STATUS = postgresql.ENUM(*CLAIM_STATUS_VALUES, name="claim_status", create_type=False)
OTP_PURPOSE = postgresql.ENUM(*OTP_PURPOSE_VALUES, name="otp_purpose", create_type=False)

ALL_ENUMS = (ITEM_KIND, ITEM_STATUS, CLAIM_STATUS, OTP_PURPOSE)


def upgrade() -> None:
    bind = op.get_bind()

    # pg_trgm must exist before any gin_trgm_ops index below.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # Create every enum type exactly once, up front.
    for enum in ALL_ENUMS:
        enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('building', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'building', name='uq_locations_name_building')
    )
    op.create_index('ix_locations_name_trgm', 'locations', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('roll_number', sa.String(length=20), nullable=False),
    sa.Column('batch', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=10), nullable=False),
    sa.Column('branch', sa.String(length=10), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', ITEM_KIND, nullable=False),
    sa.Column('status', ITEM_STATUS, server_default='reported', nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_items_category_id', 'items', ['category_id'], unique=False)
    op.create_index('ix_items_description_trgm', 'items', ['description'], unique=False, postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.create_index('ix_items_kind', 'items', ['kind'], unique=False)
    op.create_index('ix_items_location_id', 'items', ['location_id'], unique=False)
    op.create_index('ix_items_name_trgm', 'items', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_items_occurred_on', 'items', ['occurred_on'], unique=False)
    op.create_index('ix_items_reporter_id', 'items', ['reporter_id'], unique=False)
    op.create_index('ix_items_status', 'items', ['status'], unique=False)
    op.create_index('ix_items_status_kind_occurred', 'items', ['status', 'kind', 'occurred_on'], unique=False)
    op.create_table('otp_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', OTP_PURPOSE, nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_tokens_user_purpose', 'otp_tokens', ['user_id', 'purpose'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('claimant_id', sa.Integer(), nullable=False),
    sa.Column('status', CLAIM_STATUS, server_default='pending', nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claimant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'claimant_id', name='uq_claims_item_claimant')
    )
    op.create_index('ix_claims_claimant_id', 'claims', ['claimant_id'], unique=False)
    op.create_index('ix_claims_item_id', 'claims', ['item_id'], unique=False)
    op.create_index('ix_claims_status', 'claims', ['status'], unique=False)
    op.create_table('item_status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('from_status', ITEM_STATUS, nullable=True),
    sa.Column('to_status', ITEM_STATUS, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_item_status_events_item_id', 'item_status_events', ['item_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_item_status_events_item_id', table_name='item_status_events')
    op.drop_table('item_status_events')
    op.drop_index('ix_claims_status', table_name='claims')
    op.drop_index('ix_claims_item_id', table_name='claims')
    op.drop_index('ix_claims_claimant_id', table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_otp_tokens_user_purpose', table_name='otp_tokens')
    op.drop_table('otp_tokens')
    op.drop_index('ix_items_status_kind_occurred', table_name='items')
    op.drop_index('ix_items_status', table_name='items')
    op.drop_index('ix_items_reporter_id', table_name='items')
    op.drop_index('ix_items_occurred_on', table_name='items')
    op.drop_index('ix_items_name_trgm', table_name='items', postgresql_using='gin')
    op.drop_index('ix_items_location_id', table_name='items')
    op.drop_index('ix_items_kind', table_name='items')
    op.drop_index('ix_items_description_trgm', table_name='items', postgresql_using='gin')
    op.drop_index('ix_items_category_id', table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_locations_name_trgm', table_name='locations', postgresql_using='gin')
    op.drop_table('locations')
    op.drop_table('categories')
    # ### end Alembic commands ###

    # Drop the enum types now that nothing references them.
    bind = op.get_bind()
    for enum in reversed(ALL_ENUMS):
        enum.drop(bind, checkfirst=True)

    # pg_trgm is deliberately left installed: it may predate this migration or
    # be used by other schemas in the same database.
